"""Voeg IAM provisioning events toe

Revision ID: 6157155ddaf2
Revises: cc89d6919894
Create Date: 2026-07-26 23:41:18.911727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6157155ddaf2'
down_revision = 'cc89d6919894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iam_provisioning_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iam_provisioning_events')
    # ### end Alembic commands ###
