"""Hernoem id naar user_id

Revision ID: 6d401d140947
Revises: ae6291e2c9d3
Create Date: 2026-04-27 15:45:27.140063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d401d140947'
down_revision = 'ae6291e2c9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id', new_column_name='user_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id', new_column_name='id')
