"""User rol toegevoegd aan User Model

Revision ID: cc89d6919894
Revises: acc935107028
Create Date: 2026-07-26 12:35:30.242123

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc89d6919894'
down_revision = 'acc935107028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=False, server_default='user'))
    op.alter_column('users', 'role', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###